<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$helper = $this->helper('Magesture\CountDown\Helper\Data');
$getProductListShow = $helper->getProductListShow();
$getProductListSaleStartLabel = $helper->getProductListSaleStartLabel();
$getProductListSaleEndLabel = $helper->getProductListSaleEndLabel();
$selectCountDowncustomergroup = strtolower($helper->getCustomerGroup());
$selectCountDownStoreGroup = strtolower($helper->getStoreGroup());
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <script type="text/javascript">
		function getCountDownString(currentTime,countDownStartDate,productId,days){
			var d = new Date();
			var currentTime = Date.parse(d.toGMTString());
			var countDownStartDate = countDownStartDate * 1000;
		    currentTime = currentTime + 1000;
		    var distance = countDownStartDate - currentTime;
		    if(days){
		    	var days = Math.floor(distance / (1000 * 60 * 60 * 24))+1;
		    }else{
		    	var days = Math.floor(distance / (1000 * 60 * 60 * 24));
		    }
		    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
		    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
		    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
	        if (distance < 0) {
	        	return "";
	        }else{
				return days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
	        }
		}
	</script>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                    	<div class="count-down">
                    	<?php
	                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	                        $customerSession = $objectManager->get('Magento\Customer\Model\Session');
 							$currentCustomergroupId = strtolower($customerSession->getcustomer_group_id());
 							$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
    						$currentStoreId = strtolower($storeManager->getStore()->getId());
 							if ((strpos($selectCountDowncustomergroup, $currentCustomergroupId) !== false) && (strpos($selectCountDownStoreGroup, $currentStoreId) !== false) ) {
							  if($getProductListShow){
	                        $objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
                            if($_product->getTypeId() == "configurable" || $_product->getTypeId() == "grouped"){
                                $specialPriceFromDate = $_product->getcount_down_start_from();
                                $specialPriceEndDate = $_product->getcount_down_end_from();
                            }else{
                                $specialPriceFromDate = $_product->getspecial_from_date();
                                $specialPriceEndDate = $_product->getspecial_to_date();
                            }
	                        $start_date= new DateTime($specialPriceFromDate);
	                        $end_date= new DateTime($specialPriceEndDate);
	                        $current_date =new DateTime($objDate->gmtDate());
                                    if($_product->getspecial_price() || $_product->getTypeId() == "configurable" || $_product->getTypeId() == "grouped"){
                                            if(($specialPriceFromDate == "" || $specialPriceFromDate <= $objDate->gmtDate()) && ($specialPriceEndDate == "" || $specialPriceEndDate >= $objDate->gmtDate()))
                                            {
                                                $currentTime = strtotime($objDate->gmtDate()) * 1000;
                                                $countDownEndDate = strtotime($specialPriceEndDate) * 1000;
                                                $currentTime = $currentTime + 1000;
                                                $distance = $countDownEndDate - $currentTime;
                                                $days = floor($distance / (1000 * 60 * 60 * 24))+1;
                                                $hours = floor(($distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                                $minutes = floor(($distance % (1000 * 60 * 60)) / (1000 * 60));
                                                $seconds = floor(($distance % (1000 * 60)) / 1000);
                                                if($specialPriceEndDate == ""){
                                                }
                                                elseif($end_date >= $current_date){
                                                    ?>
                                                     <?php 
                                                    if (($_product->getfeatured_product_countdown() && $_product->getfeatured_product_countdown_release_date() <= $objDate->gmtDate()) || (!$_product->getfeatured_product_countdown())) {
                                                        ?>
                                                    <div class="count-down-time">
                                                        <span class="sale_end_label"><?= $getProductListSaleEndLabel ?></span>
                                                        <br>
                                                        <p id="sale_end_time<?=$_product->getId()?>" class="sale_end_time" name="sale_end_time<?=$_product->getId()?>"></p>
										                <script type="text/javascript"> 
							                            	setInterval(function() {
							                            		document.getElementById("sale_end_time<?=$_product->getId()?>").innerHTML = getCountDownString(currenttimr = <?= strtotime($objDate->gmtDate()) ?>,uniqtime =  <?= strtotime($specialPriceEndDate) ?>,productId = <?=$_product->getId()?>,days = 1);
															}, 1000);
							                            </script>
                                                    </div>
                                                    <?php
                                                    }
                                                }
                                            } elseif(($specialPriceFromDate == "" || $specialPriceFromDate <= $objDate->gmtDate()) && ($specialPriceEndDate == "" || $specialPriceEndDate <= $objDate->gmtDate()))
                                            {
                                                $currentTime = strtotime($objDate->gmtDate()) * 1000;
                                                $countDownEndDate = strtotime($specialPriceEndDate) * 1000;
                                                $countDownChnageEndDate = date('Y-m-d H:i:s', strtotime($specialPriceEndDate . ' +1 day'));
                                                $currentTime = $currentTime + 1000;
                                                $endDate = $end_date->format('d');
                                                $currentDate = $current_date->format('d');
                                                if($endDate == $currentDate)
                                                {
                                                    ?>
                                                    <?php 
                                                    if (($_product->getfeatured_product_countdown() && $_product->getfeatured_product_countdown_release_date() <= $objDate->gmtDate()) || (!$_product->getfeatured_product_countdown())) {
                                                        ?>
                                                    <div class="count-down-time">
                                                        <span class="sale_end_label"><?= $getProductListSaleEndLabel ?></span>
                                                        <br>
                                                        <p id="sale_end_time<?=$_product->getId()?>" class="sale_end_time" name="sale_end_time<?=$_product->getId()?>"></p>
							                            <script type="text/javascript"> 
							                            	setInterval(function() {
							                            		document.getElementById("sale_end_time<?=$_product->getId()?>").innerHTML = getCountDownString(currenttimr = <?= strtotime($objDate->gmtDate()) ?>,uniqtime =  <?= strtotime($countDownChnageEndDate) ?>,productId = <?=$_product->getId()?>);
															}, 1000);
							                            </script>
                                                    </div>

                                                        <?php
                                                    }
                                                    ?>
                                                    <?php
                                                }
                                            }
                                            else{
                                                if($start_date >= $current_date)
                                                {
                                                    ?>
                                                     <?php 
                                                    if (($_product->getfeatured_product_countdown() && $_product->getfeatured_product_countdown_release_date() <= $objDate->gmtDate()) || (!$_product->getfeatured_product_countdown())) {
                                                        ?>
                                                    <div class="count-down-time">
                                                        <span class="sale_start_label"><?= $getProductListSaleStartLabel ?></span>
                                                        <br>
                                                        <?php
                                                            $currentTime = strtotime($objDate->gmtDate()) * 1000;
                                                            $countDownStartDate = strtotime($specialPriceFromDate) * 1000;
                                                            $currentTime = $currentTime + 1000;
                                                            $distance = $countDownStartDate - $currentTime;
                                                            $days = floor(($distance / (1000 * 60 * 60 * 24)));
                                                            $hours = floor(($distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                                            $minutes = floor(($distance % (1000 * 60 * 60)) / (1000 * 60));
                                                            $seconds = floor(($distance % (1000 * 60)) / 1000);
                                                        ?>
                                                        <p id="sale_start_time<?=$_product->getId()?>" class="sale_start_time" name="sale_start_time<?=$_product->getId()?>"></p>
							                            <script type="text/javascript"> 
							                            	setInterval(function() {
							                            		document.getElementById("sale_start_time<?=$_product->getId()?>").innerHTML = getCountDownString(currenttimr = <?= strtotime($objDate->gmtDate()) ?>,uniqtime =  <?= strtotime($specialPriceFromDate) ?>,productId = <?=$_product->getId()?>);
															}, 1000);
							                            </script>
                                                    </div>
                                                    <?php
                                                    }
                                                }
                                            }
                                        }
                                    }
							}
							?>
                                </div>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                        <?php 
                        $featured_product_countdown = $_product->getfeatured_product_countdown();
                        $releaseDate = $_product->getfeatured_product_countdown_release_date() <= $objDate->gmtDate();
                        ?>
                        <div class="product-item-inner">
                            <?php
                            if((!$featured_product_countdown) || ($_product->getfeatured_product_countdown_release_date() <= $objDate->gmtDate()) ){
                            ?>
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else :?>
                                        <?php if ($_product->isAvailable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php
                            }
                            ?>
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>