 <?php 
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php $_product = $block->getProduct() ?>
<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
  $customer_email = $customerSession->getCustomer()->getEmail();
  $customer_id = $customerSession->getCustomer()->getId();
  $objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
  $helper = $this->helper('Magesture\CountDown\Helper\Data');
  $getNotifyAddToCrat = $helper->getNotifyAddToCrat();
  $getNotifyButtonLabel = $helper->getNotifyButtonLabel();
  $current_date =new DateTime($objDate->gmtDate());
  $releaseDateCountDown= new DateTime($_product->getfeatured_product_countdown_release_date());
   // print_r($objDate->gmtDate());
   //        echo"<pre>";
   //        print_r($_product->getfeatured_product_countdown_release_date());die;
?>
<?php if ($_product->isSaleable() && $block->hasOptions()) :?>
<?php if($_product->getfeatured_product_countdown() && $_product->getfeatured_product_countdown_release_date() >= $objDate->gmtDate()) : ?>
       <div class="bundle-actions">
         <button id="bundle-slide"
                class="action primary customize"
                type="button">
            <p id="pre_order_strat_time<?=$_product->getId()?>" class="pre_order_strat_time" name="pre_order_strat_time<?=$_product->getId()?>"></p>
            <span id="button_label"></span>
        </button>
        <?php if($_product->getfeatured_product_countdown_release_date() >= $objDate->gmtDate()):?>
        <div id="send_email">
          <form class="send_email_form" action="<?= $block->getUrl('countdown/countdown/email'); ?>" method="post">
            <input type="hidden" name="customer_email" class="customer_email" value="<?=$block->escapeHtml($customer_email) ?>">
            <input type="hidden" name="product_id" class="product_id" value="<?=$block->escapeHtml($_product->getId()) ?>">
            <button type="submit" title="Submit" class="send_email_button_customize">
                <span><?= $block->escapeHtml(__($getNotifyButtonLabel)) ?></span>
            </button>
          </form>
        </div>
        <?php endif;?> 
         <?php
            if($_product->getfeatured_product_countdown_release_date()){
              $CountDownDate = $_product->getfeatured_product_countdown_release_date();
            }else{
              $CountDownDate = "0000-00-00 00:00:00";
            }
            ?>
            <script>
                var currentTime = <?= strtotime($objDate->gmtDate()) ?> * 1000;
                var productReleaseDateCountDown = <?= strtotime($CountDownDate) ?> * 1000;
                var getNotifyAddToCrat = "<?php echo $getNotifyAddToCrat; ?>";
                var x = setInterval(function() {
                    currentTime = currentTime + 1000;
                    var distance = productReleaseDateCountDown - currentTime;
                    if(distance > 0){
                      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                      var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                      document.getElementById("pre_order_strat_time<?=$_product->getId()?>").innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
                      document.getElementById("bundle-slide").disabled = true;
                      document.getElementById("button_label").innerHTML = getNotifyAddToCrat;
                    }
                    else {
                        document.getElementById("pre_order_strat_time<?=$_product->getId()?>").innerHTML = "";
                        document.getElementById("bundle-slide").disabled = false;
                        document.getElementById("send_email").innerHTML = "";
                        document.getElementById("button_label").innerHTML = "Customize and Add to Cart";
                        clearInterval(x);
                    }
                }, 1000);
            </script>
      </div> 
      <?php else :?>
        <div class="bundle-actions">
         <button id="bundle-slide"
                class="action primary customize"
                type="button">
            <p id="pre_order_strat_time<?=$_product->getId()?>" class="pre_order_strat_time" name="pre_order_strat_time<?=$_product->getId()?>"></p>
            <span><?= $block->escapeHtml(__('Customize and Add to Cart')) ?></span>
        </button>
      </div>
      <?php endif;?> 
<?php endif;?>

<script type="text/javascript">
     require(["jquery"],function($){
        $(".send_email_button_customize").click(function(){
            var customer_email = $(".customer_email").val();
            if(customer_email == ""){
            alert("please login first!! after you have add product to notify");
            return false;
            }
        })
    })
</script>