<?php
use Magento\Catalog\ViewModel\Product\Listing\PreparePostData;
use Magento\Framework\App\ActionInterface;
?>
<?php
    $helper = $this->helper('Magesture\CountDown\Helper\Data');
    $getProductUpCrossShow = $helper->getProductUpCrossShow();
    $getProductUpCrossSaleStartLabel = $helper->getProductUpCrossSaleStartLabel();
    $getProductUpCrossSaleEndLabel = $helper->getProductUpCrossSaleEndLabel();
    $selectCountDowncustomergroup = strtolower($helper->getCustomerGroup());
    $selectCountDownStoreGroup = strtolower($helper->getStoreGroup());
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
$_item = null;
?>

<?php if ($exist):?>

<?php if ($type == 'related' || $type == 'upsell'):?>
<?php if ($type == 'related'):?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
    <?php else:?>
    <div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}'
         data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php endif; ?>
        <?php else:?>
        <div class="block <?= $block->escapeHtmlAttr($class) ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading"
                        aria-level="2"><?= $block->escapeHtml($title) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart):?>
                    <div class="block-actions">
                        <?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
                        <button type="button" class="action select"
                                data-role="select-all"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items">
                        <?php foreach ($items as $_item):?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'):?>
                                <?php if (!$_item->getRequiredOptions()):?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'):?>
                                <li class="item product product-item" style="display: none;">
                            <?php else:?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name"><a
                                            class="product-item-link"
                                            title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                    <?php if ($templateType):?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable()
                                        && $type == 'related'):?>
                                        <?php if (!$_item->getRequiredOptions()):?>
                                            <div class="field choice related"><input
                                                    type="checkbox"
                                                    class="checkbox related"
                                                    id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                                                    name="related_products[]"
                                                    value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                                <label
                                                    class="label"
                                                    for="related-checkbox<?= $block->escapeHtmlAttr(
                                                        $_item->getId()
                                                    ) ?>"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </label>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <script type="text/javascript">
                                        function getCountDownString(currentTime,countDownStartDate,productId,days){
                                            var d = new Date();
                                            var currentTime = Date.parse(d.toGMTString());
                                            var countDownStartDate = countDownStartDate * 1000;
                                            currentTime = currentTime + 1000;
                                            var distance = countDownStartDate - currentTime;
                                            if(days){
                                                var days = Math.floor(distance / (1000 * 60 * 60 * 24))+1;
                                            }else{
                                                var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                                            }
                                            var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                            var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                                            var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                                            if (distance < 0) {
                                                return "EXPIRED";
                                            }else{
                                                return days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
                                            }
                                        }
                                    </script>
                                    <div class="count-down">
                                    <?php
                                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                        $customerSession = $objectManager->get('Magento\Customer\Model\Session');
                                        $currentCustomergroupId = strtolower($customerSession->getcustomer_group_id());
                                        $storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
                                        $currentStoreId = strtolower($storeManager->getStore()->getId());
                                        if ( 1 == 1) {
                                        $objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
                                        $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
                                        if($_product->getTypeId() == "configurable"){
                                            $specialPriceFromDate = $_product->getcount_down_start_from();
                                            $specialPriceEndDate = $_product->getcount_down_end_from();
                                        }else{
                                            $specialPriceFromDate = $_product->getspecial_from_date();
                                            $specialPriceEndDate = $_product->getspecial_to_date();
                                        }
                                        $start_date= new DateTime($specialPriceFromDate);
                                        $end_date= new DateTime($_product->getspecial_to_date());
                                        $current_date =new DateTime($objDate->gmtDate());
                                        if($getProductUpCrossShow){
                                        if($specialPriceFromDate){
                                            if(($specialPriceFromDate == "" || $specialPriceFromDate <= $objDate->gmtDate()) && ($specialPriceEndDate == "" || $specialPriceEndDate >= $objDate->gmtDate()))
                                            {
                                                if($_product->getspecial_to_date() == ""){
                                                }
                                            elseif($end_date >= $current_date){
                                            ?>
                                                <div class="count-down-time">
                                                    <span class="sale_end_label"><?= $getProductUpCrossSaleEndLabel ?></span>
                                                    <p id="sale_end_time<?=$_product->getId()?>" class="sale_end_time" name="sale_end_time<?=$_product->getId()?>"></p>
                                                    <?php
                                                        $currentTime = strtotime($objDate->gmtDate()) * 1000;
                                                        $countDownEndDate = strtotime($specialPriceEndDate) * 1000;
                                                        $currentTime = $currentTime + 1000;
                                                        $distance = $countDownEndDate - $currentTime;
                                                        $days = floor($distance / (1000 * 60 * 60 * 24));
                                                        $hours = floor(($distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                                        $minutes = floor(($distance % (1000 * 60 * 60)) / (1000 * 60));
                                                        $seconds = floor(($distance % (1000 * 60)) / 1000);
                                                    ?>
                                                    <script type="text/javascript"> 
                                                            setInterval(function() {
                                                                document.getElementById("sale_end_time<?=$_product->getId()?>").innerHTML = getCountDownString(currenttimr = <?= strtotime($objDate->gmtDate()) ?>,uniqtime =  <?= strtotime($specialPriceEndDate) ?>,productId = <?=$_product->getId()?>,days = 1);
                                                            }, 1000);
                                                    </script>
                                                </div>
                                                <?php
                                            }
                                            }elseif(($specialPriceFromDate == "" || $specialPriceFromDate <= $objDate->gmtDate()) && ($specialPriceEndDate == "" || $specialPriceEndDate <= $objDate->gmtDate()))
                                            {
                                                $currentTime = strtotime($objDate->gmtDate()) * 1000;
                                                $countDownEndDate = strtotime($_product->getspecial_to_date()) * 1000;
                                                $countDownChnageEndDate = date('Y-m-d H:i:s', strtotime($specialPriceEndDate . ' +1 day'));
                                                $currentTime = $currentTime + 1000;
                                                $endDate = $end_date->format('d');
                                                $currentDate = $current_date->format('d');
                                                if($endDate == $currentDate)
                                                {
                                                    ?>
                                                    <div class="count-down-time">
                                                        <span class="sale_end_label"><?= $getProductUpCrossSaleEndLabel ?></span>
                                                        <p id="sale_end_time<?=$_product->getId()?>" class="sale_end_time" name="sale_end_time<?=$_product->getId()?>"></p>
                                                        <script type="text/javascript"> 
                                                            setInterval(function() {
                                                                document.getElementById("sale_end_time<?=$_product->getId()?>").innerHTML = getCountDownString(currenttimr = <?= strtotime($objDate->gmtDate()) ?>,uniqtime =  <?= strtotime($countDownChnageEndDate) ?>,productId = <?=$_product->getId()?>);
                                                            }, 1000);
                                                        </script>
                                                    </div>
                                                    <?php
                                                }
                                            }else{
                                                    if($start_date >= $current_date)
                                                    {
                                                    ?>
                                                        <div class="count-down-time">
                                                            <span class="sale_start_label"><?= $getProductUpCrossSaleStartLabel ?></span>
                                                            <p id="sale_start_time<?=$_product->getId()?>" class="sale_start_time" name="sale_start_time<?=$_product->getId()?>"></p>
                                                            <?php
                                                            $currentTime = strtotime($objDate->gmtDate()) * 1000;
                                                            $countDownStartDate =  strtotime($specialPriceFromDate) * 1000;
                                                            $currentTime = $currentTime + 1000;
                                                            $distance = $countDownStartDate - $currentTime;
                                                            $days = floor($distance / (1000 * 60 * 60 * 24));
                                                            $hours = floor(($distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                                            $minutes = floor(($distance % (1000 * 60 * 60)) / (1000 * 60));
                                                            $seconds = floor(($distance % (1000 * 60)) / 1000);
                                                            ?>
                                                         <script type="text/javascript"> 
                                                            setInterval(function() {
                                                                document.getElementById("sale_start_time<?=$_product->getId()?>").innerHTML = getCountDownString(currenttimr = <?= strtotime($objDate->gmtDate()) ?>,uniqtime =  <?= strtotime($specialPriceFromDate) ?>,productId = <?=$_product->getId()?>);
                                                            }, 1000);
                                                        </script>
                                                        </div>
                                                        <?php
                                                    }
                                                }
                                            }
                                        }
                                    }
                                        ?>
                                    </div>
                                    <?php if ($showAddTo || $showCart):?>
                                        <?php // phpcs:disable ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart):?>
                                                <?php if ($_item->isSaleable()):?>
                                                    <div class="actions-primary">
                                                    <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)):?>
                                                        <button
                                                            class="action tocart primary"
                                                            data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else :?>
                                                <?php
                                                /** @var $viewModel PreparePostData */
                                                $viewModel = $block->getViewModel();
                                                $postArray = $viewModel->getPostData(
                                                    $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                    ['product' => $_item->getEntityId()]
                                                );
                                                $value = $postArray['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                ?>
                                                <form data-role="tocart-form"
                                                    data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                                    action="<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"
                                                    method="post">
                                                <input type="hidden" name="product"
                                                    value="<?= /* @noEscape */ (int)$_item->getEntityId() ?>">
                                                <input type="hidden"
                                                    name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED?>"
                                                    value="<?= /* @noEscape */ $value ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                                </form>
                                                    <?php endif; ?>
                                                <?php else:?>
                                                    <?php if ($_item->getIsSalable()):?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                        </div>
                                                    <?php else:?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo):?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                                        <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php // phpcs:enable ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php if (!$block->isRedirectToCartEnabled() && $_item):?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {
                        "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                    }
                }
            }
            </script>
        <?php endif;?>
        <?php endif;?>
